benyao_arm_controller:
  ros__parameters:
    command_interfaces:
    - position
    joints:
    - benyao_arm_base_joint
    - benyao_arm_link_1_joint
    - benyao_arm_link_2_joint
    - benyao_arm_link_3_joint
    - benyao_gripper_base_joint
    state_interfaces:
    - position
    - velocity
benyao_gripper_controller:
  ros__parameters:
    command_interfaces:
    - position
    joints:
    - benyao_gripper_right_joint
    state_interfaces:
    - position
    - velocity
controller_manager:
  ros__parameters:
    benyao_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    benyao_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    update_rate: 100
