moveit.arm_slider:
  category:
  - moveit_config
  class:
    action_value_mappings:
      auto-check_tf_update_actions:
        feedback: {}
        goal: {}
        goal_default: {}
        handles: []
        result: {}
        schema:
          description: check_tf_update_actions的参数schema
          properties:
            feedback: {}
            goal:
              properties: {}
              required: []
              type: object
            result: {}
          required:
          - goal
          title: check_tf_update_actions参数
          type: object
        type: UniLabJsonCommand
      auto-moveit_joint_task:
        feedback: {}
        goal: {}
        goal_default:
          joint_names: null
          joint_positions: null
          move_group: null
          retry: 10
          speed: 1
        handles: []
        result: {}
        schema:
          description: moveit_joint_task的参数schema
          properties:
            feedback: {}
            goal:
              properties:
                joint_names:
                  type: string
                joint_positions:
                  type: string
                move_group:
                  type: string
                retry:
                  default: 10
                  type: string
                speed:
                  default: 1
                  type: string
              required:
              - move_group
              - joint_positions
              type: object
            result: {}
          required:
          - goal
          title: moveit_joint_task参数
          type: object
        type: UniLabJsonCommand
      auto-moveit_task:
        feedback: {}
        goal: {}
        goal_default:
          cartesian: false
          move_group: null
          offsets:
          - 0
          - 0
          - 0
          position: null
          quaternion: null
          retry: 10
          speed: 1
          target_link: null
        handles: []
        result: {}
        schema:
          description: moveit_task的参数schema
          properties:
            feedback: {}
            goal:
              properties:
                cartesian:
                  default: false
                  type: string
                move_group:
                  type: string
                offsets:
                  default:
                  - 0
                  - 0
                  - 0
                  type: string
                position:
                  type: string
                quaternion:
                  type: string
                retry:
                  default: 10
                  type: string
                speed:
                  default: 1
                  type: string
                target_link:
                  type: string
              required:
              - move_group
              - position
              - quaternion
              type: object
            result: {}
          required:
          - goal
          title: moveit_task参数
          type: object
        type: UniLabJsonCommand
      auto-post_init:
        feedback: {}
        goal: {}
        goal_default:
          ros_node: null
        handles: []
        result: {}
        schema:
          description: post_init的参数schema
          properties:
            feedback: {}
            goal:
              properties:
                ros_node:
                  type: string
              required:
              - ros_node
              type: object
            result: {}
          required:
          - goal
          title: post_init参数
          type: object
        type: UniLabJsonCommand
      auto-resource_manager:
        feedback: {}
        goal: {}
        goal_default:
          parent_link: null
          resource: null
        handles: []
        result: {}
        schema:
          description: resource_manager的参数schema
          properties:
            feedback: {}
            goal:
              properties:
                parent_link:
                  type: string
                resource:
                  type: string
              required:
              - resource
              - parent_link
              type: object
            result: {}
          required:
          - goal
          title: resource_manager参数
          type: object
        type: UniLabJsonCommand
      auto-wait_for_resource_action:
        feedback: {}
        goal: {}
        goal_default: {}
        handles: []
        result: {}
        schema:
          description: wait_for_resource_action的参数schema
          properties:
            feedback: {}
            goal:
              properties: {}
              required: []
              type: object
            result: {}
          required:
          - goal
          title: wait_for_resource_action参数
          type: object
        type: UniLabJsonCommand
      pick_and_place:
        feedback: {}
        goal:
          command: command
        goal_default:
          command: ''
        handles: []
        result: {}
        schema:
          description: ''
          properties:
            feedback:
              properties:
                status:
                  type: string
              required:
              - status
              title: SendCmd_Feedback
              type: object
            goal:
              properties:
                command:
                  type: string
              required:
              - command
              title: SendCmd_Goal
              type: object
            result:
              properties:
                return_info:
                  type: string
                success:
                  type: boolean
              required:
              - return_info
              - success
              title: SendCmd_Result
              type: object
          required:
          - goal
          title: SendCmd
          type: object
        type: SendCmd
      set_position:
        feedback: {}
        goal:
          command: command
        goal_default:
          command: ''
        handles: []
        result: {}
        schema:
          description: ''
          properties:
            feedback:
              properties:
                status:
                  type: string
              required:
              - status
              title: SendCmd_Feedback
              type: object
            goal:
              properties:
                command:
                  type: string
              required:
              - command
              title: SendCmd_Goal
              type: object
            result:
              properties:
                return_info:
                  type: string
                success:
                  type: boolean
              required:
              - return_info
              - success
              title: SendCmd_Result
              type: object
          required:
          - goal
          title: SendCmd
          type: object
        type: SendCmd
      set_status:
        feedback: {}
        goal:
          command: command
        goal_default:
          command: ''
        handles: []
        result: {}
        schema:
          description: ''
          properties:
            feedback:
              properties:
                status:
                  type: string
              required:
              - status
              title: SendCmd_Feedback
              type: object
            goal:
              properties:
                command:
                  type: string
              required:
              - command
              title: SendCmd_Goal
              type: object
            result:
              properties:
                return_info:
                  type: string
                success:
                  type: boolean
              required:
              - return_info
              - success
              title: SendCmd_Result
              type: object
          required:
          - goal
          title: SendCmd
          type: object
        type: SendCmd
    module: unilabos.devices.ros_dev.moveit_interface:MoveitInterface
    status_types: {}
    type: python
  config_info: []
  description: 机械臂与滑块运动系统，基于MoveIt2运动规划框架的多自由度机械臂控制设备。该系统集成机械臂和线性滑块，通过ROS2和MoveIt2实现精确的轨迹规划和协调运动控制。支持笛卡尔空间和关节空间的运动规划、碰撞检测、逆运动学求解等功能。适用于复杂的pick-and-place操作、精密装配、多工位协作等需要高精度多轴协调运动的实验室自动化应用。
  handles: []
  icon: ''
  init_param_schema:
    config:
      properties:
        device_config:
          type: string
        joint_poses:
          type: string
        moveit_type:
          type: string
        rotation:
          type: string
      required:
      - moveit_type
      - joint_poses
      type: object
    data:
      properties: {}
      required: []
      type: object
  model:
    mesh: arm_slider
    type: device
  version: 1.0.0
moveit.toyo_xyz:
  category:
  - moveit_config
  class:
    action_value_mappings:
      auto-check_tf_update_actions:
        feedback: {}
        goal: {}
        goal_default: {}
        handles: []
        result: {}
        schema:
          description: check_tf_update_actions的参数schema
          properties:
            feedback: {}
            goal:
              properties: {}
              required: []
              type: object
            result: {}
          required:
          - goal
          title: check_tf_update_actions参数
          type: object
        type: UniLabJsonCommand
      auto-moveit_joint_task:
        feedback: {}
        goal: {}
        goal_default:
          joint_names: null
          joint_positions: null
          move_group: null
          retry: 10
          speed: 1
        handles: []
        result: {}
        schema:
          description: moveit_joint_task的参数schema
          properties:
            feedback: {}
            goal:
              properties:
                joint_names:
                  type: string
                joint_positions:
                  type: string
                move_group:
                  type: string
                retry:
                  default: 10
                  type: string
                speed:
                  default: 1
                  type: string
              required:
              - move_group
              - joint_positions
              type: object
            result: {}
          required:
          - goal
          title: moveit_joint_task参数
          type: object
        type: UniLabJsonCommand
      auto-moveit_task:
        feedback: {}
        goal: {}
        goal_default:
          cartesian: false
          move_group: null
          offsets:
          - 0
          - 0
          - 0
          position: null
          quaternion: null
          retry: 10
          speed: 1
          target_link: null
        handles: []
        result: {}
        schema:
          description: moveit_task的参数schema
          properties:
            feedback: {}
            goal:
              properties:
                cartesian:
                  default: false
                  type: string
                move_group:
                  type: string
                offsets:
                  default:
                  - 0
                  - 0
                  - 0
                  type: string
                position:
                  type: string
                quaternion:
                  type: string
                retry:
                  default: 10
                  type: string
                speed:
                  default: 1
                  type: string
                target_link:
                  type: string
              required:
              - move_group
              - position
              - quaternion
              type: object
            result: {}
          required:
          - goal
          title: moveit_task参数
          type: object
        type: UniLabJsonCommand
      auto-post_init:
        feedback: {}
        goal: {}
        goal_default:
          ros_node: null
        handles: []
        result: {}
        schema:
          description: post_init的参数schema
          properties:
            feedback: {}
            goal:
              properties:
                ros_node:
                  type: string
              required:
              - ros_node
              type: object
            result: {}
          required:
          - goal
          title: post_init参数
          type: object
        type: UniLabJsonCommand
      auto-resource_manager:
        feedback: {}
        goal: {}
        goal_default:
          parent_link: null
          resource: null
        handles: []
        result: {}
        schema:
          description: resource_manager的参数schema
          properties:
            feedback: {}
            goal:
              properties:
                parent_link:
                  type: string
                resource:
                  type: string
              required:
              - resource
              - parent_link
              type: object
            result: {}
          required:
          - goal
          title: resource_manager参数
          type: object
        type: UniLabJsonCommand
      auto-wait_for_resource_action:
        feedback: {}
        goal: {}
        goal_default: {}
        handles: []
        result: {}
        schema:
          description: wait_for_resource_action的参数schema
          properties:
            feedback: {}
            goal:
              properties: {}
              required: []
              type: object
            result: {}
          required:
          - goal
          title: wait_for_resource_action参数
          type: object
        type: UniLabJsonCommand
      pick_and_place:
        feedback: {}
        goal:
          command: command
        goal_default:
          command: ''
        handles: []
        result: {}
        schema:
          description: ''
          properties:
            feedback:
              properties:
                status:
                  type: string
              required:
              - status
              title: SendCmd_Feedback
              type: object
            goal:
              properties:
                command:
                  type: string
              required:
              - command
              title: SendCmd_Goal
              type: object
            result:
              properties:
                return_info:
                  type: string
                success:
                  type: boolean
              required:
              - return_info
              - success
              title: SendCmd_Result
              type: object
          required:
          - goal
          title: SendCmd
          type: object
        type: SendCmd
      set_position:
        feedback: {}
        goal:
          command: command
        goal_default:
          command: ''
        handles: []
        result: {}
        schema:
          description: ''
          properties:
            feedback:
              properties:
                status:
                  type: string
              required:
              - status
              title: SendCmd_Feedback
              type: object
            goal:
              properties:
                command:
                  type: string
              required:
              - command
              title: SendCmd_Goal
              type: object
            result:
              properties:
                return_info:
                  type: string
                success:
                  type: boolean
              required:
              - return_info
              - success
              title: SendCmd_Result
              type: object
          required:
          - goal
          title: SendCmd
          type: object
        type: SendCmd
      set_status:
        feedback: {}
        goal:
          command: command
        goal_default:
          command: ''
        handles: []
        result: {}
        schema:
          description: ''
          properties:
            feedback:
              properties:
                status:
                  type: string
              required:
              - status
              title: SendCmd_Feedback
              type: object
            goal:
              properties:
                command:
                  type: string
              required:
              - command
              title: SendCmd_Goal
              type: object
            result:
              properties:
                return_info:
                  type: string
                success:
                  type: boolean
              required:
              - return_info
              - success
              title: SendCmd_Result
              type: object
          required:
          - goal
          title: SendCmd
          type: object
        type: SendCmd
    module: unilabos.devices.ros_dev.moveit_interface:MoveitInterface
    status_types: {}
    type: python
  config_info: []
  description: 东洋XYZ三轴运动平台，基于MoveIt2运动规划框架的精密定位设备。该设备通过ROS2和MoveIt2实现三维空间的精确运动控制，支持复杂轨迹规划、多点定位、速度控制等功能。具备高精度定位、平稳运动、实时轨迹监控等特性。适用于精密加工、样品定位、检测扫描、自动化装配等需要高精度三维运动控制的实验室和工业应用场景。
  handles: []
  icon: ''
  init_param_schema:
    config:
      properties:
        device_config:
          type: string
        joint_poses:
          type: string
        moveit_type:
          type: string
        rotation:
          type: string
      required:
      - moveit_type
      - joint_poses
      type: object
    data:
      properties: {}
      required: []
      type: object
  model:
    mesh: toyo_xyz
    type: device
  version: 1.0.0
