moveit.toyo_xyz:
  description: Toyo XYZ
  class:
    module: unilabos.devices.ros_dev.moveit_interface:MoveitInterface
    type: ros2
  model:
    type: device
    mesh: toyo_xyz

moveit.benyao_arm:
  description: Benyao Arm
  class:
    module: unilabos.devices.ros_dev.moveit_interface:MoveitInterface
    type: ros2
  model:
    type: device
    mesh: benyao_arm
  action_value_mappings:
    set_position:
      type: SendCmd
      feedback: {}
      result: {}
    pick_and_place:
      type: SendCmd
      feedback: {}
      result: {}
    set_status:
      type: SendCmd
      feedback: {}
      result: {}
